arch = [
  # core
  "hyprutils",
  "hyprlang",
  "hyprwayland-scanner",
  "hyprland",
  "xdg-desktop-portal-hyprland",
  "hypridle",
  "hyprlock",
  "hyprpicker",
  "hyprpolkitagent",

  # icon pack
  "fluent-icon-theme-git",

  # audio
  { package = "pipewire", hooks = { after_install = [
    "systemctl",
    "--user",
    "enable",
    "--now",
    "pipewire"
  ] } },

  { package = "pipewire-pulse", hooks = { after_install = [
    "systemctl",
    "--user",
    "enable",
    "--now",
    "pipewire-pulse"
  ] } },

  "pipewire-alsa",
  "pipewire-audio",
  "pipewire-jack",
  "gst-plugin-pipewire",

  { package = "wireplumber", hooks = { after_install = [
    "systemctl",
    "--user",
    "enable",
    "--now",
    "wireplumber"
  ] } },

  # terminal
  "foot",

  # wallpaper
  "swww",
  "waypaper",
  "matugen-bin",
  "adw-gtk-theme",

  # font
  "ttf-sourcecodepro-nerd",

  # clipboard
  "wl-clipboard",
  "wl-clip-persist-git",

  # gtk & qt
  "kvantum",
  "qt5ct",
  "qt6ct",
  "qt5-wayland",
  "qt6-wayland",
  "nwg-look",

  # scratchpad
  "pyprland",

  { package = "libinput-gestures", hooks = { after_install = [
    "sudo",
    "gpasswd",
    "-a",
    "shadow",
    "input"
  ] } },

  { package = "sddm", hooks = { after_install = [
    "sh",
    "-c",
    "printf '[General]\\nInputMethod=qtvirtualkeyboard\\nGreeterEnvironment=QML2_IMPORT_PATH=/usr/share/sddm/themes/silent/components/,QT_IM_MODULE=qtvirtualkeyboard\\n\\n[Theme]\\nCurrent=silent\\n' | sudo tee /etc/sddm.conf > /dev/null"
  ] } },

  { package = "sddm-silent-theme", hooks = { after_install = [
    "sh",
    "-c",
    "sudo sed -i -e '/^ConfigFile=/s/^/;/' -e '/^; ConfigFile=configs\\/rei.conf/s/^; //' /usr/share/sddm/themes/silent/metadata.desktop && sudo systemctl enable sddm"
  ] } }
]
